package com.ah.studio.blueapp.util

object Constants {
    const val SPLASH_ROUTE = "splash_route"
    const val SIGN_IN_ROUTE = "signIn_route"
    const val SIGN_UP_ROUTE = "signUp_route"
    const val HOME_ROUTE = "home_route"
    const val MY_PARKING_ROUTE = "my_parking_route"
    const val MY_BOOKING_ROUTE = "my_booking_route"
    const val SEAFARER_ROUTE = "seafarer_route"
    const val ACCOUNT_ROUTE = "account_route"
    const val CATEGORY_DETAILS_ROUTE = "category_details_route"
    const val BOAT_DETAILS_ROUTE = "boat_details_route"
    const val GALLERY_ROUTE = "gallery_route"
    const val BOAT_BOOKING_ROUTE = "boat_booking_route"
    const val SELECT_DESTINATION_ROUTE = "select_destination_route"
    const val PACKAGE_ROUTE = "package_route"
    const val PRODUCT_ROUTE = "product_route"
    const val PRODUCT_LIST_ROUTE = "product_list_route"
    const val PRODUCT_DETAILS_ROUTE = "product_details_route"
    const val CART_ROUTE = "cart_route"
    const val PAYMENT_ROUTE = "payment_route"
    const val TERMS_CONDITIONS_ROUTE = "terms_conditions_route"
    const val THANK_YOU_ROUTE = "thank_you_route"
    const val CHANGE_PASSWORD_ROUTE = "change_password_route"
    const val CAPTAIN_PAYMENT_ROUTE = "captain_payment_route"
    const val ADD_SEAFARER_ROUTE = "add_seafarer_route"
    const val EDIT_PROFILE_ROUTE = "edit_profile_route"
    const val CONTACT_US_ROUTE = "contact_us_route"
    const val REFUND_POLICY_ROUTE = "refund_policy_route"

}